import 'package:flutter/material.dart';
import '../data/badge_model.dart';
import '../data/rewards_repository.dart';

// ── Palette locale ────────────────────────────────────────────
const _violet      = Color(0xFF6D28D9);
const _violetLight = Color(0xFF8B7FE8);
const _teal        = Color(0xFF00D4C8);
const _corail      = Color(0xFFFF4D6A);
const _amber       = Color(0xFFFFB800);
const _orange      = Color(0xFFFF9100);

class BadgeService {
  BadgeService._();

  static List<AppBadge> computeBadges({
    required int longestStreak,
    required int currentStreak,
    required int totalPoints,
    required int level,
    required RewardsStats activity,
    bool isFounder = true,
  }) {
    final best = longestStreak > currentStreak ? longestStreak : currentStreak;

    return [
      // ── Régularité ─────────────────────────── tier : common/common/rare/rare/legendary/legendary

      AppBadge(
        id: 'streak_3',
        name: 'Premier élan',
        description: 'Tu avances à ton rythme — et ça se ressent.',
        hint: 'Reviens 3 jours de suite',
        category: BadgeCategory.streak,
        tier: BadgeTier.common,
        isUnlocked: best >= 3,
        gradientColors: const [_corail, _amber],
        icon: Icons.local_fire_department_rounded,
        progressCurrent: best.clamp(0, 3),
        progressGoal: 3,
        progressUnit: 'jours',
      ),
      AppBadge(
        id: 'streak_7',
        name: 'Semaine gagnée',
        description: '7 jours de régularité. C\'est du concret.',
        hint: 'Reviens 7 jours de suite',
        category: BadgeCategory.streak,
        tier: BadgeTier.common,
        isUnlocked: best >= 7,
        gradientColors: const [_amber, _corail],
        icon: Icons.whatshot_rounded,
        progressCurrent: best.clamp(0, 7),
        progressGoal: 7,
        progressUnit: 'jours',
      ),
      AppBadge(
        id: 'streak_14',
        name: '2 semaines',
        description: 'Tu construis une vraie habitude. Félicitations.',
        hint: 'Maintiens ton élan 14 jours',
        category: BadgeCategory.streak,
        tier: BadgeTier.rare,
        isUnlocked: best >= 14,
        gradientColors: const [_amber, _violetLight],
        icon: Icons.whatshot_rounded,
        progressCurrent: best.clamp(0, 14),
        progressGoal: 14,
        progressUnit: 'jours',
      ),
      AppBadge(
        id: 'streak_30',
        name: 'Un mois solide',
        description: 'Un mois entier. Tu es fiable pour toi-même.',
        hint: 'Maintiens ton élan 30 jours',
        category: BadgeCategory.streak,
        tier: BadgeTier.rare,
        isUnlocked: best >= 30,
        gradientColors: const [_violet, _teal],
        icon: Icons.emoji_events_rounded,
        progressCurrent: best.clamp(0, 30),
        progressGoal: 30,
        progressUnit: 'jours',
      ),
      AppBadge(
        id: 'streak_100',
        name: '100 jours',
        description: '100 jours : tu es un exemple pour toute la tribu.',
        hint: 'Maintiens ton élan 100 jours',
        category: BadgeCategory.streak,
        tier: BadgeTier.legendary,
        isUnlocked: best >= 100,
        gradientColors: const [_teal, _violet],
        icon: Icons.diamond_rounded,
        progressCurrent: best.clamp(0, 100),
        progressGoal: 100,
        progressUnit: 'jours',
      ),
      AppBadge(
        id: 'streak_365',
        name: 'Légende',
        description: 'Un an ensemble. Respect absolu.',
        hint: 'Maintiens ton élan 365 jours',
        category: BadgeCategory.streak,
        tier: BadgeTier.legendary,
        isUnlocked: best >= 365,
        gradientColors: const [_amber, _orange],
        icon: Icons.workspace_premium_rounded,
        progressCurrent: best.clamp(0, 365),
        progressGoal: 365,
        progressUnit: 'jours',
      ),

      // ── Progression ────────────────────────── niveaux 1-2 common, 3-4 rare, 5 legendary

      AppBadge(
        id: 'level_1',
        name: 'Explorateur',
        description: 'Tu commences l\'aventure Kolyb.',
        hint: 'Débloqué automatiquement',
        category: BadgeCategory.level,
        tier: BadgeTier.common,
        isUnlocked: level >= 1,
        gradientColors: const [_teal, _violetLight],
        icon: Icons.explore_rounded,
      ),
      AppBadge(
        id: 'level_2',
        name: 'Indépendant',
        description: 'Tu trouves ton propre rythme.',
        hint: 'Atteins le niveau 2 (101 pts)',
        category: BadgeCategory.level,
        tier: BadgeTier.common,
        isUnlocked: level >= 2,
        gradientColors: const [_violetLight, _violet],
        icon: Icons.person_rounded,
        progressCurrent: totalPoints.clamp(0, 101),
        progressGoal: 101,
        progressUnit: 'pts',
      ),
      AppBadge(
        id: 'level_3',
        name: 'Entrepreneur',
        description: 'Tu avances avec intention chaque jour.',
        hint: 'Atteins le niveau 3 (301 pts)',
        category: BadgeCategory.level,
        tier: BadgeTier.rare,
        isUnlocked: level >= 3,
        gradientColors: const [_violet, _corail],
        icon: Icons.rocket_launch_rounded,
        progressCurrent: totalPoints.clamp(0, 301),
        progressGoal: 301,
        progressUnit: 'pts',
      ),
      AppBadge(
        id: 'level_4',
        name: 'Bâtisseur',
        description: 'Tu construis quelque chose de durable.',
        hint: 'Atteins le niveau 4 (601 pts)',
        category: BadgeCategory.level,
        tier: BadgeTier.rare,
        isUnlocked: level >= 4,
        gradientColors: const [_violet, _teal],
        icon: Icons.handyman_rounded,
        progressCurrent: totalPoints.clamp(0, 601),
        progressGoal: 601,
        progressUnit: 'pts',
      ),
      AppBadge(
        id: 'level_5',
        name: 'Visionnaire',
        description: 'Tu es un modèle pour toute la communauté.',
        hint: 'Atteins le niveau 5 (1001 pts)',
        category: BadgeCategory.level,
        tier: BadgeTier.legendary,
        isUnlocked: level >= 5,
        gradientColors: const [_amber, _orange],
        icon: Icons.auto_awesome_rounded,
        progressCurrent: totalPoints.clamp(0, 1001),
        progressGoal: 1001,
        progressUnit: 'pts',
      ),

      // ── Flash ─────────────────────────────────

      AppBadge(
        id: 'flash_1',
        name: 'Première action',
        description: 'Ta première micro-tâche Flash. Bien démarré !',
        hint: 'Complète 1 tâche Flash',
        category: BadgeCategory.flash,
        tier: BadgeTier.common,
        isUnlocked: activity.flashTasksDone >= 1,
        gradientColors: const [_amber, _orange],
        icon: Icons.bolt_rounded,
        progressCurrent: activity.flashTasksDone.clamp(0, 1),
        progressGoal: 1,
        progressUnit: 'tâche',
      ),
      AppBadge(
        id: 'flash_10',
        name: 'Flash x10',
        description: '10 micro-victoires. Tu maîtrises le Flash.',
        hint: 'Complète 10 tâches Flash',
        category: BadgeCategory.flash,
        tier: BadgeTier.common,
        isUnlocked: activity.flashTasksDone >= 10,
        gradientColors: const [_orange, _amber],
        icon: Icons.bolt_rounded,
        progressCurrent: activity.flashTasksDone.clamp(0, 10),
        progressGoal: 10,
        progressUnit: 'tâches',
      ),
      AppBadge(
        id: 'flash_50',
        name: 'Flash en série',
        description: '50 actions concrètes. Tu fais bouger les choses.',
        hint: 'Complète 50 tâches Flash',
        category: BadgeCategory.flash,
        tier: BadgeTier.rare,
        isUnlocked: activity.flashTasksDone >= 50,
        gradientColors: const [_amber, _corail],
        icon: Icons.flash_on_rounded,
        progressCurrent: activity.flashTasksDone.clamp(0, 50),
        progressGoal: 50,
        progressUnit: 'tâches',
      ),
      AppBadge(
        id: 'flash_100',
        name: 'Maître Flash',
        description: '100 tâches Flash. Tu es inarrêtable.',
        hint: 'Complète 100 tâches Flash',
        category: BadgeCategory.flash,
        tier: BadgeTier.legendary,
        isUnlocked: activity.flashTasksDone >= 100,
        gradientColors: const [_corail, _amber],
        icon: Icons.electric_bolt_rounded,
        progressCurrent: activity.flashTasksDone.clamp(0, 100),
        progressGoal: 100,
        progressUnit: 'tâches',
      ),

      // ── Check-ins ─────────────────────────────

      AppBadge(
        id: 'checkin_1',
        name: 'Premier bilan',
        description: 'Tu prends le temps de t\'écouter. C\'est rare.',
        hint: 'Fais ton premier check-in',
        category: BadgeCategory.checkin,
        tier: BadgeTier.common,
        isUnlocked: activity.checkinsCount >= 1,
        gradientColors: const [_teal, _violetLight],
        icon: Icons.wb_sunny_rounded,
        progressCurrent: activity.checkinsCount.clamp(0, 1),
        progressGoal: 1,
        progressUnit: 'check-in',
      ),
      AppBadge(
        id: 'checkin_7',
        name: '7 rendez-vous',
        description: 'Tu honores tes rendez-vous avec toi-même.',
        hint: 'Complète 7 check-ins',
        category: BadgeCategory.checkin,
        tier: BadgeTier.common,
        isUnlocked: activity.checkinsCount >= 7,
        gradientColors: const [_teal, _violet],
        icon: Icons.calendar_today_rounded,
        progressCurrent: activity.checkinsCount.clamp(0, 7),
        progressGoal: 7,
        progressUnit: 'check-ins',
      ),
      AppBadge(
        id: 'checkin_30',
        name: 'Bilan du mois',
        description: '30 check-ins. Tu te connais de mieux en mieux.',
        hint: 'Complète 30 check-ins',
        category: BadgeCategory.checkin,
        tier: BadgeTier.rare,
        isUnlocked: activity.checkinsCount >= 30,
        gradientColors: const [_violetLight, _teal],
        icon: Icons.self_improvement_rounded,
        progressCurrent: activity.checkinsCount.clamp(0, 30),
        progressGoal: 30,
        progressUnit: 'check-ins',
      ),
      AppBadge(
        id: 'checkin_100',
        name: 'Miroir fidèle',
        description: '100 check-ins. Tu es ton meilleur allié.',
        hint: 'Complète 100 check-ins',
        category: BadgeCategory.checkin,
        tier: BadgeTier.legendary,
        isUnlocked: activity.checkinsCount >= 100,
        gradientColors: const [_violet, _teal],
        icon: Icons.insights_rounded,
        progressCurrent: activity.checkinsCount.clamp(0, 100),
        progressGoal: 100,
        progressUnit: 'check-ins',
      ),

      // ── Projets ───────────────────────────────

      AppBadge(
        id: 'project_first',
        name: 'Premier projet',
        description: 'Tu as posé les bases de quelque chose de concret.',
        hint: 'Crée ton premier projet dans le Kanban',
        category: BadgeCategory.project,
        tier: BadgeTier.common,
        isUnlocked: activity.projectsCreated >= 1,
        gradientColors: const [_violet, _violetLight],
        icon: Icons.inventory_2_rounded,
        progressCurrent: activity.projectsCreated.clamp(0, 1),
        progressGoal: 1,
        progressUnit: 'projet',
      ),
      AppBadge(
        id: 'project_complete',
        name: 'Premier succès',
        description: 'Tu as terminé ce que tu avais commencé. Bravo.',
        hint: 'Termine ton premier projet',
        category: BadgeCategory.project,
        tier: BadgeTier.rare,
        isUnlocked: activity.projectsCompleted >= 1,
        gradientColors: const [_amber, _violet],
        icon: Icons.check_circle_rounded,
        progressCurrent: activity.projectsCompleted.clamp(0, 1),
        progressGoal: 1,
        progressUnit: 'projet',
      ),
      AppBadge(
        id: 'project_five',
        name: 'Série de 5',
        description: '5 projets bouclés. Tu livres, et ça se voit.',
        hint: 'Termine 5 projets',
        category: BadgeCategory.project,
        tier: BadgeTier.legendary,
        isUnlocked: activity.projectsCompleted >= 5,
        gradientColors: const [_corail, _violet],
        icon: Icons.workspace_premium_rounded,
        progressCurrent: activity.projectsCompleted.clamp(0, 5),
        progressGoal: 5,
        progressUnit: 'projets',
      ),

      // ── Communauté ────────────────────────────

      AppBadge(
        id: 'community_first',
        name: 'Prise de parole',
        description: 'Tu as partagé ta voix dans Le Salon. Merci.',
        hint: 'Publie ton premier message dans Le Salon',
        category: BadgeCategory.community,
        tier: BadgeTier.common,
        isUnlocked: activity.postsCount >= 1,
        gradientColors: const [_violetLight, _corail],
        icon: Icons.forum_rounded,
        progressCurrent: activity.postsCount.clamp(0, 1),
        progressGoal: 1,
        progressUnit: 'post',
      ),
      AppBadge(
        id: 'community_10',
        name: 'Voix du Salon',
        description: '10 contributions. Tu animes la tribu.',
        hint: 'Publie 10 messages dans Le Salon',
        category: BadgeCategory.community,
        tier: BadgeTier.rare,
        isUnlocked: activity.postsCount >= 10,
        gradientColors: const [_violet, _violetLight],
        icon: Icons.people_rounded,
        progressCurrent: activity.postsCount.clamp(0, 10),
        progressGoal: 10,
        progressUnit: 'posts',
      ),

      // ── Spéciaux ──────────────────────────────

      AppBadge(
        id: 'first_step',
        name: 'Premier pas',
        description: 'Tu as démarré. C\'est souvent le plus dur.',
        hint: 'Gagne ton premier point',
        category: BadgeCategory.special,
        tier: BadgeTier.common,
        isUnlocked: totalPoints >= 1,
        gradientColors: const [_teal, _violetLight],
        icon: Icons.directions_walk_rounded,
        progressCurrent: totalPoints.clamp(0, 1),
        progressGoal: 1,
        progressUnit: 'pt',
      ),
      AppBadge(
        id: 'momentum',
        name: 'Momentum',
        description: 'Tu accumules de l\'élan, ça se sent !',
        hint: 'Atteins 50 points',
        category: BadgeCategory.special,
        tier: BadgeTier.rare,
        isUnlocked: totalPoints >= 50,
        gradientColors: const [_violetLight, _corail],
        icon: Icons.trending_up_rounded,
        progressCurrent: totalPoints.clamp(0, 50),
        progressGoal: 50,
        progressUnit: 'pts',
      ),
      AppBadge(
        id: 'comeback',
        name: 'Relevé',
        description: 'Tu t\'es relevé après une pause. C\'est ça, la vraie force.',
        hint: 'Reviens après une interruption (+15 pts)',
        category: BadgeCategory.special,
        tier: BadgeTier.common,
        isUnlocked: totalPoints >= 15,
        gradientColors: const [_corail, _amber],
        icon: Icons.trending_up_rounded,
      ),
      AppBadge(
        id: 'founder',
        name: 'Membre Fondateur',
        description: 'Tu fais partie des premiers à croire en Kolyb. Merci.',
        hint: 'Réservé aux membres fondateurs',
        category: BadgeCategory.special,
        tier: BadgeTier.legendary,
        isUnlocked: isFounder,
        gradientColors: const [_amber, _orange],
        icon: Icons.stars_rounded,
      ),
    ];
  }

  static List<AppBadge> unlockedBadges(List<AppBadge> badges) =>
      badges.where((b) => b.isUnlocked).toList();

  static List<AppBadge> byCategory(
    List<AppBadge> badges,
    BadgeCategory category,
  ) =>
      badges.where((b) => b.category == category).toList();
}
